"""Add is_pinned field to Note

Revision ID: 77243ad049c8
Revises: 
Create Date: 2025-07-02 09:15:21.140828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77243ad049c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_pinned', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('is_pinned')

    # ### end Alembic commands ###
